---
title: "Introducing Meteor"
format: html
---

OPTED Meteor (Media Text Open Registry) is an inventory for European journalistic texts and is part of the EU-funded Project OPTED where researchers work towards the creation of a new European research infrastructure for the study of political communication in Europe. 

## News Sources

## Software tools

You can find tools here.

### Using Meteor in the Classroom

Beyond a resource for scholarly research, Meteor can also be used in courses with (under-)graduate students.
We successfully conducted a master level seminar where students learned about comparative research, as well as the theoretical foundations of media systems. The course consisted of two parts. The first part discussed selected readings about comparative research and (hybrid) media systems. The second part put these theoretical considerations into practice by systematically comparing countries based on the landscape of available news sources. For that purpose, groups of students chose two media systems in Europe and defined the subsection of news media that they were interested in (e.g., traditional print press). Meteor allowed the students to compare the two systems based on their sample of news sources.

You can find all the ressources for the course we designed at <https://meteor.opted.eu/guides/teaching-materials#downloads>