project:
  type: website

website:
  favicon: /img/OPTED_logo_transparent.png
  #body-footer: | 
  #  ![](/img/eu_funded.png)
  title: "OPTED Tutorials"
  navbar:
    logo: /img/OPTED_logo_transparent.png
    background: white
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - meteor.qmd
  page-footer:  
    left: | 
      ![](/img/eu_funded.png){width=60%}
    right: 
      - icon: github
        href: https://github.com/opted-eu
      - icon: twitter 
        href: https://twitter.com/opted_h2020

format:
  html:
    theme: 
    - cosmo
    - custom.scss
    css: styles.css
    toc: true


